name: Lint commits

on:
  pull_request:

permissions: {}

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: true
      LEFTHOOK_QUIET: meta,execution
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@eb2f5cb41b0a8175dad2f797e3daca6fe7795a19 # v2.4.2
      - run: lefthook run commit-msgs-on-pr-branch --no-tty
