name: Release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release-please:
    name: Release please
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4.2.0
        id: release-please
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
    outputs:
      release-created: ${{ steps.release-please.outputs.release_created }}
      sha: ${{ steps.release-please.outputs.sha }}

  build-dist:
    name: Build dists
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release-created
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          ref: ${{ needs.release-please.outputs.sha }}
      - uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
        with:
          activate-environment: true
      - name: Create release assets
        run: |
          set -euxo pipefail
          uv pip install --upgrade build
          uv run python3 -m build
          ls dist
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: dist
          path: dist/

  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build-dist
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0  # v5.0.0
        with:
          name: dist
      - run: ls dist
      #- uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e  # v1.13.0
      #  with:
      #    repository-url: https://test.pypi.org/legacy/
